language: node_js
node_js:
  - "11"

install:
  - yarn --frozen-lockfile
script:
  - yarn test

jobs:
  include:
    - name: deploy
      script:
        - git remote set-url origin https://${GH_TOKEN}@github.com/Luchanso/dependencies-heatmap.git > /dev/null 2>&1
        - yarn release
        - git push origin master --quiet --follow-tags
      if: branch = feature/cicd AND commit_message =~ /^((?!chore\(release\). \d\.\d\.\d).)*$/
