language: node_js
node_js:
  - "11"

install:
  - yarn --frozen-lockfile
script:
  - yarn test

jobs:
  include:
    - name: deploy
      script:
        - git remote set-url origin https://${GH_TOKEN}@github.com/Luchanso/dependencies-heatmap.git > /dev/null 2>&1
        - yarn release
        - git checkout -b feature/cicd-test # for test
        - git push origin feature/cicd-test --quiet
        # - git push --follow-tags origin master
      if: branch = feature/cicd
    - name: ci/cd test
      script:
        - env
        - echo '~~~~~~~~~~~~~~~~~~~ NOT WORKING ~~~~~~~~~~~~~~~~~~~~~~~~'
        - exit 1
      if: 'branch = feature/cicd-test AND commit_message =~ /^((?!chore\(release\): \d\.\d\.\d).)*$/'
