language: node_js
node_js:
  - "11"

install:
  - yarn --frozen-lockfile
script:
  - yarn test

jobs:
  include:
    - name: deploy
      script:
        - git remote set-url origin https://${GH_TOKEN}@github.com/Luchanso/dependencies-heatmap.git > /dev/null 2>&1
        - yarn release
        - git push origin feature/cicd-test --quiet # --follow-tags
    - name: test
      script: exit 1
      if: >
        branch = feature/cicd-test AND commit_message =~ /^((?!chore\(release\): \d\.\d\.\d).)*$/
