language: node_js
node_js:
  - "11"

jobs:
  include:
    - name: install
      install: yarn --frozen-lockfile
    - name: test
      script: yarn test
    - name: deploy
      script:
        - git remote set-url origin https://${GH_TOKEN}@github.com/Luchanso/dependencies-heatmap.git > /dev/null 2>&1
        - yarn release
        - git push --quiet --follow-tags origin HEAD
      if: >
        branch = master AND commit_message =~ /^((?!chore\(release\): \d\.\d\.\d).)*$/ AND type = push
